module.exports = {
  0: "SOZIOÖKONOMISCHE ENTWICKLUNG",
  1: "VERWENDUNG VON STICKSTOFFDÜNGER",
  2: "ERNÄHRUNG",
  3: "ANBAU",
  4: "TECHNOLOGIE ODER DIÄT",
  5: "LEBENSMITTELVERSCHWENDUNG",
  6: "WASSERNUTZUNG",
  7: "FLEISCHKONSUM"
};